export const unoTheme = {
    colors: {
        green: '#13AE5C',
        charcoal: '#2C2C2C',
        stone: {
            50: '#fafaf9',
            200: '#e7e5e4',
            400: '#a8a29e',
        },
        neutral: {
            400: '#a3a3a3',
            700: '#404040',
        },
        zinc: {
            300: '#d4d4d8',
        },
        slate: {
            500: '#64748B',
        },
        indigo: {
            500: '#6366f1',
            600: '#4f46e5',
        },
        white: '#FFFFFF',
        black: '#000000',
    },
    textColor: {
        'green': '#13AE5C',
        'charcoal': '#2C2C2C',
        'stone-50': '#fafaf9',
        'stone-200': '#e7e5e4',
        'stone-400': '#a8a29e',
        'neutral-400': '#a3a3a3',
        'neutral-700': '#404040',
        'zinc-300': '#d4d4d8',
        'black': '#000000',
        'white': '#FFFFFF',
    },
    fontFamily: {
        archivo: '"Archivo Narrow", sans-serif',
        roboto: '"Roboto", sans-serif',
        inter: '"Inter", sans-serif',
        'material': ['Material Symbols Outlined'],
    },
    fontSize: {
        xs: ['12px', '16px'],
        sm: ['14px', '20px'],
        base: ['16px', '24px'],
        lg: ['18px', '28px'],
        xl: ['20px', '28px'],
    },
    fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
    },
    boxShadow: {
        sm: '0 1px 3px rgba(0, 0, 0, 0.1)',
        md: '0 3px 12px rgba(0, 0, 0, 0.08)',
        lg: '0 10px 20px rgba(0, 0, 0, 0.1)',
    },
    borderWidth: {
        '': 'border-width: 1px;',
        '2': 'border-width: 2px;',
        'b': 'border-bottom-width: 1px;',
    },
    borderRadius: {
        'none': 'border-radius: 0px',
        'rounded-sm': 'border-radius: 2px',
        'rounded': 'border-radius: 4px',
        'rounded-md': 'border-radius: 8px',
        'rounded-lg': 'border-radius: 12px',
        'rounded-xl': 'border-radius: 16px',
    },
    extend: {
        margin: {
            m: {
                '0': 'margin: 0;',
                '1': 'margin: 4px;',
                '2': 'margin: 8px;',
                '2.5': 'margin: 10px;',
                '3': 'margin: 12px;',
                '3.5': 'margin: 14px;',
                '4': 'margin: 16px;',
                '5': 'margin: 20px;',
                '6': 'margin: 24px;',
                '7': 'margin: 28px;',
                '8': 'margin: 32px;',
                '9': 'margin: 36px;',
                '10': 'margin: 40px;',
            },
            mt: {
                '1': 'margin-top: 4px;',
                '2': 'margin-top: 8px;',
                '2.5': 'margin-top: 10px;',
                '3': 'margin-top: 12px;',
                '3.5': 'margin-top: 14px;',
                '4': 'margin-top: 16px;',
                '5': 'margin-top: 20px;',
                '6': 'margin-top: 24px;',
                '7': 'margin-top: 28px;',
                '8': 'margin-top: 32px;',
                '9': 'margin-top: 36px;',
                '10': 'margin-top: 40px;',
            },
            mb: {
                '[1px]': 'margin-bottom: 1px;',
                '1': 'margin-bottom: 4px;',
                '2': 'margin-bottom: 8px;',
                '2.5': 'margin-bottom: 10px;',
                '3': 'margin-bottom: 12px;',
                '3.5': 'margin-bottom: 14px;',
                '4': 'margin-bottom: 16px;',
                '5': 'margin-bottom: 20px;',
                '6': 'margin-bottom: 24px;',
                '7': 'margin-bottom: 28px;',
                '8': 'margin-bottom: 32px;',
                '9': 'margin-bottom: 36px;',
                '10': 'margin-bottom: 40px;',
            },
            mr: {
                '1': 'margin-right: 4px;',
                '2': 'margin-right: 8px;',
                '2.5': 'margin-right: 10px;',
                '3': 'margin-right: 12px;',
                '3.5': 'margin-right: 14px;',
                '4': 'margin-right: 16px;',
                '5': 'margin-right: 20px;',
                '6': 'margin-right: 24px;',
                '7': 'margin-right: 28px;',
                '8': 'margin-right: 32px;',
                '9': 'margin-right: 36px;',
                '10': 'margin-right: 40px;',
            },
            ml: {
                '1': 'margin-left: 4px;',
                '2': 'margin-left: 8px;',
                '2.5': 'margin-left: 10px;',
                '3': 'margin-left: 12px;',
                '3.5': 'margin-left: 14px;',
                '4': 'margin-left: 16px;',
                '5': 'margin-left: 20px;',
                '6': 'margin-left: 24px;',
                '7': 'margin-left: 28px;',
                '8': 'margin-left: 32px;',
                '9': 'margin-left: 36px;',
                '10': 'margin-left: 40px;',
            },
            mx: {
                '1': 'margin-right: 4px; margin-left: 4px;',
                '2': 'margin-right: 8px; margin-left: 8px;',
                '2.5': 'margin-right: 10px; margin-left: 10px;',
                '3': 'margin-right: 12px; margin-left: 12px;',
                '3.5': 'margin-right: 14px; margin-left: 14px;',
                '4': 'margin-right: 16px; margin-left: 16px;',
                '5': 'margin-right: 20px; margin-left: 20px;',
                '6': 'margin-right: 24px; margin-left: 24px;',
                '7': 'margin-right: 28px; margin-left: 28px;',
                '8': 'margin-right: 32px; margin-left: 32px;',
                '9': 'margin-right: 36px; margin-left: 36px;',
                '10': 'margin-right: 40px; margin-left: 40px;',
            },
            my: {
                '1': 'margin-top: 4px; margin-bottom: 4px;',
                '2': 'margin-top: 8px; margin-bottom: 8px;',
                '2.5': 'margin-top: 10px; margin-bottom: 10px;',
                '3': 'margin-top: 12px; margin-bottom: 12px;',
                '3.5': 'margin-top: 14px; margin-bottom: 14px;',
                '4': 'margin-top: 16px; margin-bottom: 16px;',
                '5': 'margin-top: 20px; margin-bottom: 20px;',
                '6': 'margin-top: 24px; margin-bottom: 24px;',
                '7': 'margin-top: 28px; margin-bottom: 28px;',
                '8': 'margin-top: 32px; margin-bottom: 32px;',
                '9': 'margin-top: 36px; margin-bottom: 36px;',
                '10': 'margin-top: 40px; margin-bottom: 40px;',
            },
            ms: {
                '1': 'margin-inline-start: 4px;',
                '2': 'margin-inline-start: 8px;',
                '3': 'margin-inline-start: 12px;',
                '4': 'margin-inline-start: 16px;',
                '5': 'margin-inline-start: 20px;',
                '6': 'margin-inline-start: 24px;',
                '7': 'margin-inline-start: 28px;',
                '8': 'margin-inline-start: 32px;',
                '9': 'margin-inline-start: 36px;',
                '10': 'margin-inline-start: 40px;',
            },
            me: {
                '1': 'margin-inline-end: 4px;',
                '2': 'margin-inline-end: 8px;',
                '3': 'margin-inline-end: 12px;',
                '4': 'margin-inline-end: 16px;',
                '5': 'margin-inline-end: 20px;',
                '6': 'margin-inline-end: 24px;',
                '7': 'margin-inline-end: 28px;',
                '8': 'margin-inline-end: 32px;',
                '9': 'margin-inline-end: 36px;',
                '10': 'margin-inline-end: 40px;',
            },
        },
        padding: {
            p: {
                '0': 'padding: 0;',
                '1': 'padding: 4px;',
                '1.5': 'padding: 6px;',
                '2': 'padding: 8px;',
                '2.5': 'padding: 10px;',
                '3': 'padding: 12px;',
                '3.5': 'padding: 14px;',
                '4': 'padding: 16px;',
                '5': 'padding: 20px;',
                '6': 'padding: 24px;',
                '7': 'padding: 28px;',
                '8': 'padding: 32px;',
                '9': 'padding: 36px;',
                '10': 'padding: 40px;',
            },
            pt: {
                '1': 'padding-top: 4px;',
                '1.5': 'padding-top: 6px;',
                '2': 'padding-top: 8px;',
                '2.5': 'padding-top: 10px;',
                '3': 'padding-top: 12px;',
                '3.5': 'padding-top: 14px;',
                '4': 'padding-top: 16px;',
                '5': 'padding-top: 20px;',
                '6': 'padding-top: 24px;',
                '7': 'padding-top: 28px;',
                '8': 'padding-top: 32px;',
                '9': 'padding-top: 36px;',
                '10': 'padding-top: 40px;',
            },
            pb: {
                '1': 'padding-bottom: 4px;',
                '1.5': 'padding-bottom: 6px;',
                '2': 'padding-bottom: 8px;',
                '2.5': 'padding-bottom: 10px;',
                '3': 'padding-bottom: 12px;',
                '3.5': 'padding-bottom: 14px;',
                '4': 'padding-bottom: 16px;',
                '5': 'padding-bottom: 20px;',
                '6': 'padding-bottom: 24px;',
                '7': 'padding-bottom: 28px;',
                '8': 'padding-bottom: 32px;',
                '9': 'padding-bottom: 36px;',
                '10': 'padding-bottom: 40px;',
            },
            pr: {
                '1': 'padding-right: 4px;',
                '1.5': 'padding-right: 6px;',
                '2': 'padding-right: 8px;',
                '2.5': 'padding-right: 10px;',
                '3': 'padding-right: 12px;',
                '3.5': 'padding-right: 14px;',
                '4': 'padding-right: 16px;',
                '5': 'padding-right: 20px;',
                '6': 'padding-right: 24px;',
                '7': 'padding-right: 28px;',
                '8': 'padding-right: 32px;',
                '9': 'padding-right: 36px;',
                '10': 'padding-right: 40px;',
            },
            pl: {
                '1': 'padding-left: 4px;',
                '1.5': 'padding-left: 6px;',
                '2': 'padding-left: 8px;',
                '2.5': 'padding-left: 10px;',
                '3': 'padding-left: 12px;',
                '3.5': 'padding-left: 14px;',
                '4': 'padding-left: 16px;',
                '5': 'padding-left: 20px;',
                '6': 'padding-left: 24px;',
                '7': 'padding-left: 28px;',
                '8': 'padding-left: 32px;',
                '9': 'padding-left: 36px;',
                '10': 'padding-left: 40px;',
            },
            px: {
                '1': 'padding-right: 4px; padding-left: 4px;',
                '1.5': 'padding-right: 6px; padding-left: 6px;',
                '2': 'padding-right: 8px; padding-left: 8px;',
                '2.5': 'padding-right: 10px; padding-left: 10px;',
                '3': 'padding-right: 12px; padding-left: 12px;',
                '3.5': 'padding-right: 14px; padding-left: 14px;',
                '4': 'padding-right: 16px; padding-left: 16px;',
                '5': 'padding-right: 20px; padding-left: 20px;',
                '6': 'padding-right: 24px; padding-left: 24px;',
                '7': 'padding-right: 28px; padding-left: 28px;',
                '8': 'padding-right: 32px; padding-left: 32px;',
                '9': 'padding-right: 36px; padding-left: 36px;',
                '10': 'padding-right: 40px; padding-left: 40px;',
            },
            py: {
                '1': 'padding-top: 4px; padding-bottom: 4px;',
                '1.5': 'padding-top: 6px; padding-bottom: 6px;',
                '2': 'padding-top: 8px; padding-bottom: 8px;',
                '2.5': 'padding-top: 10px; padding-bottom: 10px;',
                '3': 'padding-top: 12px; padding-bottom: 12px;',
                '3.5': 'padding-top: 14px; padding-bottom: 14px;',
                '4': 'padding-top: 16px; padding-bottom: 16px;',
                '5': 'padding-top: 20px; padding-bottom: 20px;',
                '6': 'padding-top: 24px; padding-bottom: 24px;',
                '7': 'padding-top: 28px; padding-bottom: 28px;',
                '8': 'padding-top: 32px; padding-bottom: 32px;',
                '9': 'padding-top: 36px; padding-bottom: 36px;',
                '10': 'padding-top: 40px; padding-bottom: 40px;',
            },
            ps: {
                '1': 'padding-inline-start: 4px;',
                '2': 'padding-inline-start: 8px;',
                '3': 'padding-inline-start: 12px;',
                '4': 'padding-inline-start: 16px;',
                '5': 'padding-inline-start: 20px;',
                '6': 'padding-inline-start: 24px;',
                '7': 'padding-inline-start: 28px;',
                '8': 'padding-inline-start: 32px;',
                '9': 'padding-inline-start: 36px;',
                '10': 'padding-inline-start: 40px;',
            },
            pe: {
                '1': 'padding-inline-end: 4px;',
                '2': 'padding-inline-end: 8px;',
                '3': 'padding-inline-end: 12px;',
                '4': 'padding-inline-end: 16px;',
                '5': 'padding-inline-end: 20px;',
                '6': 'padding-inline-end: 24px;',
                '7': 'padding-inline-end: 28px;',
                '8': 'padding-inline-end: 32px;',
                '9': 'padding-inline-end: 36px;',
                '10': 'padding-inline-end: 40px;',
            },
        },
    },
};
const buttonColors = {
    primary: 'rgba(53, 52, 60, 1)',
    secondary: 'rgba(0, 123, 255, 1)',
    warning: 'rgba(255, 149, 0, 1)',
    success: 'rgba(52, 199, 89, 1)',
    error: 'rgba(255, 59, 48, 1)',
    info: 'rgba(48, 176, 199, 1)',
};
const buttonHoverColors = {
    primaryHover: 'rgba(117, 117, 117, 1)',
    secondaryHover: 'rgba(50, 173, 230, 1)',
    warningHover: 'rgba(184, 107, 0, 1)',
    successHover: 'rgba(38, 146, 65, 1)',
    purpleHover: 'rgba(114, 66, 193, 1)',
    errorHover: 'rgba(224, 11, 0, 1)',
    infoHover: 'rgba(0, 199, 190, 1)',
    greyHover: 'rgba(139, 140, 149, 1)',
};
const mainColors = {
    beach: '#FFFAF3',
    beachDark: '#E2CFBF',
    canyon: '#D9B59B',
    canyonLight: '#F9E9E1',
    canyonDark: '#AD754E',
    forest: '#042E30',
    forestLight: '#125E5C',
    forestDark: '#011111',
    mintLight: '#E8F3F2',
    newForest: '#158481',
    valley: '#66D210',
    valleyLight: '#A1FF3E',
    valleyDark: '#309600',
};
const accentColors = {
    blue: '#2582E2',
    blueLight: '#80CFFF',
    blueMedium: '#0441A3',
    blueDark: '#00246B',
    orange: '#FFA614',
    orangeLight: '#FFECB6',
    orangeMedium: '#D86C00',
    orangeDark: '#9E4000',
    purple: '#9E67EC',
    purpleLight: '#D2BBFF',
    purpleMedium: '#581EC6',
    purpleDark: '#31007F',
    teal: '#6FD5E4',
    tealLight: '#B3FDFF',
    tealMedium: '#058EAD',
    tealDark: '#00536D',
    red: '#FF4C35',
    redLight: '#FFA1A1',
    redMedium: '#D11915',
    redDark: '#7C0000',
};
const allGreys = {
    grey100: '#F7F7FC',
    grey200: '#EFF0F6',
    grey300: '#E4E5EE',
    grey400: '#DADCE2',
    grey500: '#C7C7CC',
    grey600: '#B0B1B7',
    grey700: '#8B8C95',
    grey800: '#636366',
    grey900: '#35343C',
};
const greys = {
    100: '#F7F7FC',
    200: '#EFF0F6',
    300: '#E4E5EE',
    400: '#DADCE2',
    500: '#C7C7CC',
    600: '#B0B1B7',
    700: '#8B8C95',
    800: '#636366',
    900: '#35343C',
};
const colors = Object.assign(Object.assign(Object.assign(Object.assign(Object.assign(Object.assign({}, buttonColors), buttonHoverColors), accentColors), mainColors), allGreys), { grey: Object.assign({}, greys), body: 'rgba(70, 70, 72, 1)', white: '#FFFFFF', light: 'rgba(240, 240, 240, 1)', textDisabled: 'rgba(139, 140, 149, 1)', disabled: 'rgba(0, 0, 0, 0.12)', warmGrey: '#FCF9F6', black: '#000000' });
export { buttonColors, buttonHoverColors, colors };
